spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: #jdbc:mariadb://mibot.cpk5wmyll2nc.ap-northeast-2.rds.amazonaws.com/mibot?characterEncoding=UTF-8&serverTimezone=UTC
        jdbc:mariadb://localhost:3306/mibotdb?characterEncoding=UTF-8&serverTimezone=UTC

    username: root #mibot
    password: root #mibot803

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  servlet:
    multipart:
      enabled: true
      location: C:\Users\bitcamp\EI\mibot-front\public\image_save\
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 1MB



security:
  jwt:
    token:
      security-key:secret-key
      expiration-length:3600000

server:
  port: 8080

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG